-- This is designed for PostgreSQL.

-- temporary table. Might only be used for testing
CREATE TABLE incoming_packages (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  data json NOT NULL
  date_added timestamp without time zone NOT NULL default timezone('UTC'::text, now())
);



INSERT INTO incoming_packages (data) values (
'{
  "name": "foo.example.org",
  "os": "FreeBSD",
  "version": "12.0-RELEASE-p8",
  "repo": "http://pkg.freebsd.org/FreeBSD:12:amd64/latest/",
  "packages": {
    "package": [
      "apr-1.6.5.1.6.1_1",
      [
        "bacula9-client-9.4.3"
      ],
      [
        "bash-5.0.7"
      ]
    ]
  }
}');

-- I am purposely not creating tables for os, version, and repo.
--
--CREATE TABLE os (
--  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--  name text NOT NULL
--);
  
CREATE TABLE host (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name    text NOT NULL,
  os      text NOT NULL,
  version text NOT NULL,
  repo    text NOT NULL,
  UNIQUE (name)
);

CREATE TABLE package (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  UNIQUE (name)
);

CREATE TABLE package_version (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  package_id int NOT NULL references package(id) ON DELETE CASCADE,
  version  text NOT NULL,
  UNIQUE (package_id, version)
);

CREATE TABLE host_package (
  host_id            int NOT NULL references host(id)            ON DELETE CASCADE,
  package_version_id int NOT NULL references package_version(id) ON DELETE CASCADE,
  UNIQUE(host_id, package_version_id)
);
